### ISSUE TITLE
Especificar o que é o XPTO Planning - Gerência de Projeto

### ISSUE THREAD

**Issue by g0dkar** [g0dkar/talpi#1]
Fazer a especificação do projeto necessária para a disciplina de Gerência de Projeto (prof. Adalton)

A especificação pedida por ele pode ser uma apresentação simples onde é determinado o projeto, o que ele faz, que problema ele tenta resolver, como ele tenta resolver, **que áreas da gestão ele contempla** (pelo menos 3) e um overview de como ele funciona _(não necessariamente nessa ordem)_

**Comment by g0dkar** [comment]
É bom seguir o overview que tá lá na issue #2

**Comment by g0dkar** [comment]
@KelvinCampelo Tu manja de deixar menas feia? Fiz aquele velho template bolado preto-e-branco hehehe

**Comment by KelvinCampelo** [comment]
@g0dkar Sim! hahaha
